### ISSUE TITLE
Use SVProgressHUD wisely! ...

### ISSUE THREAD

**Issue by matejkramny** [TransitApp/SVProgressHUD#395]
From the readme:

> Use SVProgressHUD wisely! Only use it if you absolutely need to perform a task before taking the user forward. Bad use case examples: pull to refresh, infinite scrolling, sending message.

Can you explain why?

It is a *progress* HUD so loading something over the network is a viable case for using such library.

**Comment by honkmaster** [comment]
I agree that one could think thats a viable use case. However, in my opinion, loading from something over the network is one of the worst cases where to use such a library. This is due to the following reasons: A user might be one a bad network connection. Then loading of data could take a long time (sometimes multiple seconds). Blocking the UI meanwhile using the HUD is not good. Here a user could do some other tasks in your app while waiting for the data to arrive, e.g. in a Twitter client a user should be able to read the timeline (with old tweets) while waiting for new data. Here i would use `[UIApplication setNetworkActivityIndicatorVisible:]` to indicate loading in the background. I would only show the HUD when for example your updating the UI (e.g. after loading the tweets) and the user is explicitly not allowed to interact.

**Comment by matejkramny** [comment]
@honkmaster Interesting.. A while back I was using MBProgressHUD, and attached a UITapGestureRecogniser to it. Whenever the user tapped on the HUD, I cancelled the network connection and got out of the user's way.

**Comment by honkmaster** [comment]
You could do the same using the `SVProgressHUDDidTouchDownInsideNotification`. However, think about your iOS-experience. Have you seen any popular, network-connected app doing something like this (i don't think so)?

**Comment by matejkramny** [comment]
Yeah you're right..

I'd be interested in finding the **right** solution for these issues though, it has never crossed my mind that its bad UX.

**Comment by honkmaster** [comment]
As mentioned before, my usage:
- Use `SVProgressHUD` wisely and only if you want to show progress and prohibit user interaction (by using a background mask)
- Perform loading and all hardcore tasks on a background thread
- When loading network data show the networkActivityIndicator

**Comment by matejkramny** [comment]
:+1: Alright. Thanks for responding quickly.
