### ISSUE TITLE
CocoaPods 1.1.3 Release

### ISSUE THREAD

**Issue by x2on** [TransitApp/SVProgressHUD#413]
Please make a CocoaPods 1.1.3 Release!

Thanks

**Comment by honkmaster** [comment]
N'Abend Felix. Ich hatte gedacht das wäre schon passiert, hatte die Podspec nicht umsonst aktualisiert. Laut meiner Bash-History hatte ich es auch zu Cocoapods übertragen. Naja, irgendwas ist dabei wohl schiefgegangen. Ich hohle es nachher (nach Feierabend) nach. 

Beste Grüße

**Comment by honkmaster** [comment]
Hi, we are aware of a problem regarding the Podfile (e.g. #449). It seems that the `SVProgressHUD.bundle` is not copied to the "Copy Bundle Resources" Build Phase. Due to this continuing problem we are searching for someone that could check and help with this problem. We are not using Cocoapods on our own and are happy for pull request.
