### ISSUE TITLE
showWithMaskType:

### ISSUE THREAD

**Issue by vinnybad** [TransitApp/SVProgressHUD#464]
Previously, there was a showWithMaskType: method and this was removed.  Our app uses this method and we preferred not setting a default mask type.  

Was there a technical limitation or something else that caused this method to be removed?  If not, is it possible to deprecate the method if that's no longer the preferred way?  

Thanks for this amazing library.  Several of my apps depend on it.

**Comment by paul-moon** [comment]
+1

**Comment by matt** [comment]
I use this library for a project as well. I agree with @vinnybad; deprecating this method would be a preferred solution.

+1

**Comment by honkmaster** [comment]
Within the scope of #384 We decided to simplify 'SVProgressHud'. From @samvermette and mine perspective the 'showWithMaskType:' appendix was kind of unnecessary ballast for many methods. This is especially true because, from the feedback we got, many people always use the same mask. I decided to make a "clean" cut and not deprecate the methods. Explanation of this is, that at the moment I am the only maintainer and won't to keep the cognitive load as small as possible.

**Comment by honkmaster** [comment]
BTW: This is again work in progress, the Cocoapods release is not scheduled yet.

**Comment by vinnybad** [comment]
@honkmaster ok this makes sense.  Thanks for the update on this...

I was just a little surprised to see it go away entirely and not deprecated, that's all.

**Comment by patoroco** [comment]
Same problem here. We use a wrapper over SVProgressHUD and it's easy to change it in only one place, but IMHO, a __deprecated macro should be better to this kind of disruptive changes, isn't it?
