### ISSUE TITLE
missing something with using cocoapods

### ISSUE THREAD

**Issue by jumpingfrog0** [TransitApp/SVProgressHUD#499]
Did you update the latest version in cocoapods repository?
I can't find `SVProgressHUDStyle` in the code which import with cocoapods. It seems to be a long time ago version.
master:
![image](https://cloud.githubusercontent.com/assets/7556575/10687266/6e1476bc-799e-11e5-805f-6526c3708f6b.png)
cocoapods:
![image](https://cloud.githubusercontent.com/assets/7556575/10687283/803b8aba-799e-11e5-9169-e4f8b9a9600a.png)

**Comment by kapoorsahil** [comment]
The podspec has not been updated for quite long now.
Use `pod 'SVProgressHUD', :head` to get latest code via cocoapods.

**Comment by honkmaster** [comment]
I updated the pod, please be aware that 2.0 is in beta status right now.

**Comment by honkmaster** [comment]
Hi, we are aware of a problem regarding the Podfile (e.g. #449). It seems that the `SVProgressHUD.bundle` is not copied to the "Copy Bundle Resources" Build Phase. Due to this continuing problem we are searching for someone that could check and help with this problem. We are not using Cocoapods on our own and are happy for pull request.
