### ISSUE TITLE
Using Swift Bridging Header + Carthage Complains about Missing Submodule

### ISSUE THREAD

**Issue by tomarra** [TransitApp/SVProgressHUD#509]
Getting the following error when putting SVProgressHUD in my project via Carthage.

`Missing submodule 'SVProgressHUD.SVProgressHUD_Framework'`

My project uses Swift so in my Bridging Header I have the following

`#import <SVProgressHUD/SVProgressHUD-Framework.h>`

Anything that I should be doing differently or is this an actual bug in the framework?

**Comment by honkmaster** [comment]
Hi,

the `SVProgressHUD-Framework/SVProgressHUD-Framework.h` was removed due to this PR (https://github.com/TransitApp/SVProgressHUD/pull/500). I am not using carthage myself and was thinking that @flovilmart (the original author auf the carthage support) was aware what he was doing. Maybe he can say why he removed the header.

**Comment by flovilmart** [comment]
You can use now `@import SVProgressHUD` or `#import <SVProgressHUD/SVProgressHUD.h>` as recommended by apple. 
The orignal version was actually a mistake due to my lack of understanding with modules :)

**Comment by honkmaster** [comment]
@tomarra Is this a sufficient solution?

**Comment by tomarra** [comment]
Since it was Obj-C I figured it had to go in the bridging header. I never thought about a import in the VC I was using it in. That worked perfectly. Thanks @honkmaster & @flovilmart !

**Comment by flovilmart** [comment]
Now it guaranties proper functioning in swift and objective-c, no matter where you put your import :)

**Comment by honkmaster** [comment]
Perfect!
