### ISSUE TITLE
2.0-beta Pod error

### ISSUE THREAD

**Issue by Dids** [TransitApp/SVProgressHUD#513]
Getting the following error:

```
[!] Unable to load a podspec from `SVProgressHUD.podspec`, skipping:

Pod::DSLError
```

**Comment by Dids** [comment]
False alarm, had to update Cocoapods.

**Comment by honkmaster** [comment]
Hi, we are aware of a problem regarding the Podfile (e.g. #449). It seems that the `SVProgressHUD.bundle` is not copied to the "Copy Bundle Resources" Build Phase. Due to this continuing problem we are searching for someone that could check and help with this problem. We are not using Cocoapods on our own and are happy for pull request.
